/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arithmetic Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.ArithmeticDependency#getOperation <em>Operation</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.ArithmeticDependency#getRelationalOp <em>Relational Op</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.ArithmeticDependency#getResult <em>Result</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getArithmeticDependency()
 * @model
 * @generated
 */
public interface ArithmeticDependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(Operation)
   * @see es.us.isa.idl.idl.IdlPackage#getArithmeticDependency_Operation()
   * @model containment="true"
   * @generated
   */
  Operation getOperation();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.ArithmeticDependency#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(Operation value);

  /**
   * Returns the value of the '<em><b>Relational Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational Op</em>' attribute.
   * @see #setRelationalOp(String)
   * @see es.us.isa.idl.idl.IdlPackage#getArithmeticDependency_RelationalOp()
   * @model
   * @generated
   */
  String getRelationalOp();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.ArithmeticDependency#getRelationalOp <em>Relational Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational Op</em>' attribute.
   * @see #getRelationalOp()
   * @generated
   */
  void setRelationalOp(String value);

  /**
   * Returns the value of the '<em><b>Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result</em>' attribute.
   * @see #setResult(String)
   * @see es.us.isa.idl.idl.IdlPackage#getArithmeticDependency_Result()
   * @model
   * @generated
   */
  String getResult();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.ArithmeticDependency#getResult <em>Result</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Result</em>' attribute.
   * @see #getResult()
   * @generated
   */
  void setResult(String value);

} // ArithmeticDependency
