/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Predefined Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getNot <em>Not</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getPredefDepType <em>Predef Dep Type</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getPredefDepElements <em>Predef Dep Elements</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getGeneralPredefinedDependency()
 * @model
 * @generated
 */
public interface GeneralPredefinedDependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(String)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralPredefinedDependency_Not()
   * @model
   * @generated
   */
  String getNot();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #getNot()
   * @generated
   */
  void setNot(String value);

  /**
   * Returns the value of the '<em><b>Predef Dep Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predef Dep Type</em>' attribute.
   * @see #setPredefDepType(String)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralPredefinedDependency_PredefDepType()
   * @model
   * @generated
   */
  String getPredefDepType();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getPredefDepType <em>Predef Dep Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predef Dep Type</em>' attribute.
   * @see #getPredefDepType()
   * @generated
   */
  void setPredefDepType(String value);

  /**
   * Returns the value of the '<em><b>Predef Dep Elements</b></em>' containment reference list.
   * The list contents are of type {@link es.us.isa.idl.idl.GeneralPredicate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predef Dep Elements</em>' containment reference list.
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralPredefinedDependency_PredefDepElements()
   * @model containment="true"
   * @generated
   */
  EList<GeneralPredicate> getPredefDepElements();

} // GeneralPredefinedDependency
