/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.GeneralPredicate#getFirstClause <em>First Clause</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.GeneralPredicate#getClauseContinuation <em>Clause Continuation</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getGeneralPredicate()
 * @model
 * @generated
 */
public interface GeneralPredicate extends EObject
{
  /**
   * Returns the value of the '<em><b>First Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Clause</em>' containment reference.
   * @see #setFirstClause(GeneralClause)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralPredicate_FirstClause()
   * @model containment="true"
   * @generated
   */
  GeneralClause getFirstClause();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralPredicate#getFirstClause <em>First Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Clause</em>' containment reference.
   * @see #getFirstClause()
   * @generated
   */
  void setFirstClause(GeneralClause value);

  /**
   * Returns the value of the '<em><b>Clause Continuation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Clause Continuation</em>' containment reference.
   * @see #setClauseContinuation(GeneralClauseContinuation)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralPredicate_ClauseContinuation()
   * @model containment="true"
   * @generated
   */
  GeneralClauseContinuation getClauseContinuation();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralPredicate#getClauseContinuation <em>Clause Continuation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Clause Continuation</em>' containment reference.
   * @see #getClauseContinuation()
   * @generated
   */
  void setClauseContinuation(GeneralClauseContinuation value);

} // GeneralPredicate
