/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Clause Continuation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.GeneralClauseContinuation#getLogicalOp <em>Logical Op</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.GeneralClauseContinuation#getAdditionalElements <em>Additional Elements</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getGeneralClauseContinuation()
 * @model
 * @generated
 */
public interface GeneralClauseContinuation extends EObject
{
  /**
   * Returns the value of the '<em><b>Logical Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logical Op</em>' attribute.
   * @see #setLogicalOp(String)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralClauseContinuation_LogicalOp()
   * @model
   * @generated
   */
  String getLogicalOp();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralClauseContinuation#getLogicalOp <em>Logical Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logical Op</em>' attribute.
   * @see #getLogicalOp()
   * @generated
   */
  void setLogicalOp(String value);

  /**
   * Returns the value of the '<em><b>Additional Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additional Elements</em>' containment reference.
   * @see #setAdditionalElements(GeneralPredicate)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralClauseContinuation_AdditionalElements()
   * @model containment="true"
   * @generated
   */
  GeneralPredicate getAdditionalElements();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralClauseContinuation#getAdditionalElements <em>Additional Elements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additional Elements</em>' containment reference.
   * @see #getAdditionalElements()
   * @generated
   */
  void setAdditionalElements(GeneralPredicate value);

} // GeneralClauseContinuation
