/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>General Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.GeneralTerm#getNot <em>Not</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.GeneralTerm#getParam <em>Param</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getGeneralTerm()
 * @model
 * @generated
 */
public interface GeneralTerm extends EObject
{
  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(String)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralTerm_Not()
   * @model
   * @generated
   */
  String getNot();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralTerm#getNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #getNot()
   * @generated
   */
  void setNot(String value);

  /**
   * Returns the value of the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' containment reference.
   * @see #setParam(ParamValueRelation)
   * @see es.us.isa.idl.idl.IdlPackage#getGeneralTerm_Param()
   * @model containment="true"
   * @generated
   */
  ParamValueRelation getParam();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.GeneralTerm#getParam <em>Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' containment reference.
   * @see #getParam()
   * @generated
   */
  void setParam(ParamValueRelation value);

} // GeneralTerm
