/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see es.us.isa.idl.idl.IdlFactory
 * @model kind="package"
 * @generated
 */
public interface IdlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "idl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "https://github.com/isa-group/IDL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "idl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IdlPackage eINSTANCE = es.us.isa.idl.idl.impl.IdlPackageImpl.init();

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.ModelImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DEPENDENCIES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.DependencyImpl <em>Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.DependencyImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 1;

  /**
   * The feature id for the '<em><b>Dep</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__DEP = 0;

  /**
   * The number of structural features of the '<em>Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.GeneralTermImpl <em>General Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.GeneralTermImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralTerm()
   * @generated
   */
  int GENERAL_TERM = 9;

  /**
   * The feature id for the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_TERM__NOT = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_TERM__PARAM = 1;

  /**
   * The number of structural features of the '<em>General Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_TERM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.RelationalDependencyImpl <em>Relational Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.RelationalDependencyImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getRelationalDependency()
   * @generated
   */
  int RELATIONAL_DEPENDENCY = 2;

  /**
   * The feature id for the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_DEPENDENCY__NOT = GENERAL_TERM__NOT;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_DEPENDENCY__PARAM = GENERAL_TERM__PARAM;

  /**
   * The feature id for the '<em><b>Param1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_DEPENDENCY__PARAM1 = GENERAL_TERM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Relational Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_DEPENDENCY__RELATIONAL_OP = GENERAL_TERM_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Param2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_DEPENDENCY__PARAM2 = GENERAL_TERM_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Relational Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_DEPENDENCY_FEATURE_COUNT = GENERAL_TERM_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.ArithmeticDependencyImpl <em>Arithmetic Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.ArithmeticDependencyImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getArithmeticDependency()
   * @generated
   */
  int ARITHMETIC_DEPENDENCY = 3;

  /**
   * The feature id for the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETIC_DEPENDENCY__OPERATION = 0;

  /**
   * The feature id for the '<em><b>Relational Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETIC_DEPENDENCY__RELATIONAL_OP = 1;

  /**
   * The feature id for the '<em><b>Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETIC_DEPENDENCY__RESULT = 2;

  /**
   * The number of structural features of the '<em>Arithmetic Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITHMETIC_DEPENDENCY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.OperationImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 4;

  /**
   * The feature id for the '<em><b>First Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__FIRST_PARAM = 0;

  /**
   * The feature id for the '<em><b>Operation Continuation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPERATION_CONTINUATION = 1;

  /**
   * The feature id for the '<em><b>Opening Parenthesis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPENING_PARENTHESIS = 2;

  /**
   * The feature id for the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPERATION = 3;

  /**
   * The feature id for the '<em><b>Closing Parenthesis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__CLOSING_PARENTHESIS = 4;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.OperationContinuationImpl <em>Operation Continuation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.OperationContinuationImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getOperationContinuation()
   * @generated
   */
  int OPERATION_CONTINUATION = 5;

  /**
   * The feature id for the '<em><b>Arith Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_CONTINUATION__ARITH_OP = 0;

  /**
   * The feature id for the '<em><b>Additional Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_CONTINUATION__ADDITIONAL_PARAMS = 1;

  /**
   * The number of structural features of the '<em>Operation Continuation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_CONTINUATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.ConditionalDependencyImpl <em>Conditional Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.ConditionalDependencyImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getConditionalDependency()
   * @generated
   */
  int CONDITIONAL_DEPENDENCY = 6;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_DEPENDENCY__CONDITION = 0;

  /**
   * The feature id for the '<em><b>Consequence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_DEPENDENCY__CONSEQUENCE = 1;

  /**
   * The number of structural features of the '<em>Conditional Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_DEPENDENCY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.GeneralPredicateImpl <em>General Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.GeneralPredicateImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralPredicate()
   * @generated
   */
  int GENERAL_PREDICATE = 7;

  /**
   * The feature id for the '<em><b>First Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_PREDICATE__FIRST_CLAUSE = 0;

  /**
   * The feature id for the '<em><b>Clause Continuation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_PREDICATE__CLAUSE_CONTINUATION = 1;

  /**
   * The number of structural features of the '<em>General Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_PREDICATE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.GeneralClauseImpl <em>General Clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.GeneralClauseImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralClause()
   * @generated
   */
  int GENERAL_CLAUSE = 8;

  /**
   * The feature id for the '<em><b>First Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE__FIRST_ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE__NOT = 1;

  /**
   * The feature id for the '<em><b>Opening Parenthesis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE__OPENING_PARENTHESIS = 2;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE__PREDICATE = 3;

  /**
   * The feature id for the '<em><b>Closing Parenthesis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE__CLOSING_PARENTHESIS = 4;

  /**
   * The number of structural features of the '<em>General Clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.ParamValueRelationImpl <em>Param Value Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.ParamValueRelationImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getParamValueRelation()
   * @generated
   */
  int PARAM_VALUE_RELATION = 11;

  /**
   * The number of structural features of the '<em>Param Value Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_VALUE_RELATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.ParamImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getParam()
   * @generated
   */
  int PARAM = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__NAME = PARAM_VALUE_RELATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>String Values</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__STRING_VALUES = PARAM_VALUE_RELATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Pattern String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__PATTERN_STRING = PARAM_VALUE_RELATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Boolean Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__BOOLEAN_VALUE = PARAM_VALUE_RELATION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Relational Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__RELATIONAL_OP = PARAM_VALUE_RELATION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Double Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__DOUBLE_VALUE = PARAM_VALUE_RELATION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = PARAM_VALUE_RELATION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.GeneralClauseContinuationImpl <em>General Clause Continuation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.GeneralClauseContinuationImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralClauseContinuation()
   * @generated
   */
  int GENERAL_CLAUSE_CONTINUATION = 12;

  /**
   * The feature id for the '<em><b>Logical Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE_CONTINUATION__LOGICAL_OP = 0;

  /**
   * The feature id for the '<em><b>Additional Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE_CONTINUATION__ADDITIONAL_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>General Clause Continuation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_CLAUSE_CONTINUATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link es.us.isa.idl.idl.impl.GeneralPredefinedDependencyImpl <em>General Predefined Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see es.us.isa.idl.idl.impl.GeneralPredefinedDependencyImpl
   * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralPredefinedDependency()
   * @generated
   */
  int GENERAL_PREDEFINED_DEPENDENCY = 13;

  /**
   * The feature id for the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_PREDEFINED_DEPENDENCY__NOT = 0;

  /**
   * The feature id for the '<em><b>Predef Dep Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_PREDEFINED_DEPENDENCY__PREDEF_DEP_TYPE = 1;

  /**
   * The feature id for the '<em><b>Predef Dep Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_PREDEFINED_DEPENDENCY__PREDEF_DEP_ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>General Predefined Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERAL_PREDEFINED_DEPENDENCY_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see es.us.isa.idl.idl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link es.us.isa.idl.idl.Model#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencies</em>'.
   * @see es.us.isa.idl.idl.Model#getDependencies()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Dependencies();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency</em>'.
   * @see es.us.isa.idl.idl.Dependency
   * @generated
   */
  EClass getDependency();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.Dependency#getDep <em>Dep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dep</em>'.
   * @see es.us.isa.idl.idl.Dependency#getDep()
   * @see #getDependency()
   * @generated
   */
  EReference getDependency_Dep();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.RelationalDependency <em>Relational Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relational Dependency</em>'.
   * @see es.us.isa.idl.idl.RelationalDependency
   * @generated
   */
  EClass getRelationalDependency();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.RelationalDependency#getParam1 <em>Param1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param1</em>'.
   * @see es.us.isa.idl.idl.RelationalDependency#getParam1()
   * @see #getRelationalDependency()
   * @generated
   */
  EReference getRelationalDependency_Param1();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.RelationalDependency#getRelationalOp <em>Relational Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Relational Op</em>'.
   * @see es.us.isa.idl.idl.RelationalDependency#getRelationalOp()
   * @see #getRelationalDependency()
   * @generated
   */
  EAttribute getRelationalDependency_RelationalOp();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.RelationalDependency#getParam2 <em>Param2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param2</em>'.
   * @see es.us.isa.idl.idl.RelationalDependency#getParam2()
   * @see #getRelationalDependency()
   * @generated
   */
  EReference getRelationalDependency_Param2();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.ArithmeticDependency <em>Arithmetic Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arithmetic Dependency</em>'.
   * @see es.us.isa.idl.idl.ArithmeticDependency
   * @generated
   */
  EClass getArithmeticDependency();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.ArithmeticDependency#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operation</em>'.
   * @see es.us.isa.idl.idl.ArithmeticDependency#getOperation()
   * @see #getArithmeticDependency()
   * @generated
   */
  EReference getArithmeticDependency_Operation();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.ArithmeticDependency#getRelationalOp <em>Relational Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Relational Op</em>'.
   * @see es.us.isa.idl.idl.ArithmeticDependency#getRelationalOp()
   * @see #getArithmeticDependency()
   * @generated
   */
  EAttribute getArithmeticDependency_RelationalOp();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.ArithmeticDependency#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Result</em>'.
   * @see es.us.isa.idl.idl.ArithmeticDependency#getResult()
   * @see #getArithmeticDependency()
   * @generated
   */
  EAttribute getArithmeticDependency_Result();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see es.us.isa.idl.idl.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.Operation#getFirstParam <em>First Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First Param</em>'.
   * @see es.us.isa.idl.idl.Operation#getFirstParam()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_FirstParam();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.Operation#getOperationContinuation <em>Operation Continuation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operation Continuation</em>'.
   * @see es.us.isa.idl.idl.Operation#getOperationContinuation()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_OperationContinuation();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.Operation#getOpeningParenthesis <em>Opening Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Opening Parenthesis</em>'.
   * @see es.us.isa.idl.idl.Operation#getOpeningParenthesis()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_OpeningParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.Operation#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operation</em>'.
   * @see es.us.isa.idl.idl.Operation#getOperation()
   * @see #getOperation()
   * @generated
   */
  EReference getOperation_Operation();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.Operation#getClosingParenthesis <em>Closing Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Closing Parenthesis</em>'.
   * @see es.us.isa.idl.idl.Operation#getClosingParenthesis()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_ClosingParenthesis();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.OperationContinuation <em>Operation Continuation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation Continuation</em>'.
   * @see es.us.isa.idl.idl.OperationContinuation
   * @generated
   */
  EClass getOperationContinuation();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.OperationContinuation#getArithOp <em>Arith Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Arith Op</em>'.
   * @see es.us.isa.idl.idl.OperationContinuation#getArithOp()
   * @see #getOperationContinuation()
   * @generated
   */
  EAttribute getOperationContinuation_ArithOp();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.OperationContinuation#getAdditionalParams <em>Additional Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Additional Params</em>'.
   * @see es.us.isa.idl.idl.OperationContinuation#getAdditionalParams()
   * @see #getOperationContinuation()
   * @generated
   */
  EReference getOperationContinuation_AdditionalParams();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.ConditionalDependency <em>Conditional Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional Dependency</em>'.
   * @see es.us.isa.idl.idl.ConditionalDependency
   * @generated
   */
  EClass getConditionalDependency();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.ConditionalDependency#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see es.us.isa.idl.idl.ConditionalDependency#getCondition()
   * @see #getConditionalDependency()
   * @generated
   */
  EReference getConditionalDependency_Condition();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.ConditionalDependency#getConsequence <em>Consequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Consequence</em>'.
   * @see es.us.isa.idl.idl.ConditionalDependency#getConsequence()
   * @see #getConditionalDependency()
   * @generated
   */
  EReference getConditionalDependency_Consequence();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.GeneralPredicate <em>General Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Predicate</em>'.
   * @see es.us.isa.idl.idl.GeneralPredicate
   * @generated
   */
  EClass getGeneralPredicate();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.GeneralPredicate#getFirstClause <em>First Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First Clause</em>'.
   * @see es.us.isa.idl.idl.GeneralPredicate#getFirstClause()
   * @see #getGeneralPredicate()
   * @generated
   */
  EReference getGeneralPredicate_FirstClause();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.GeneralPredicate#getClauseContinuation <em>Clause Continuation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Clause Continuation</em>'.
   * @see es.us.isa.idl.idl.GeneralPredicate#getClauseContinuation()
   * @see #getGeneralPredicate()
   * @generated
   */
  EReference getGeneralPredicate_ClauseContinuation();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.GeneralClause <em>General Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Clause</em>'.
   * @see es.us.isa.idl.idl.GeneralClause
   * @generated
   */
  EClass getGeneralClause();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.GeneralClause#getFirstElement <em>First Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First Element</em>'.
   * @see es.us.isa.idl.idl.GeneralClause#getFirstElement()
   * @see #getGeneralClause()
   * @generated
   */
  EReference getGeneralClause_FirstElement();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.GeneralClause#getNot <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Not</em>'.
   * @see es.us.isa.idl.idl.GeneralClause#getNot()
   * @see #getGeneralClause()
   * @generated
   */
  EAttribute getGeneralClause_Not();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.GeneralClause#getOpeningParenthesis <em>Opening Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Opening Parenthesis</em>'.
   * @see es.us.isa.idl.idl.GeneralClause#getOpeningParenthesis()
   * @see #getGeneralClause()
   * @generated
   */
  EAttribute getGeneralClause_OpeningParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.GeneralClause#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see es.us.isa.idl.idl.GeneralClause#getPredicate()
   * @see #getGeneralClause()
   * @generated
   */
  EReference getGeneralClause_Predicate();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.GeneralClause#getClosingParenthesis <em>Closing Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Closing Parenthesis</em>'.
   * @see es.us.isa.idl.idl.GeneralClause#getClosingParenthesis()
   * @see #getGeneralClause()
   * @generated
   */
  EAttribute getGeneralClause_ClosingParenthesis();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.GeneralTerm <em>General Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Term</em>'.
   * @see es.us.isa.idl.idl.GeneralTerm
   * @generated
   */
  EClass getGeneralTerm();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.GeneralTerm#getNot <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Not</em>'.
   * @see es.us.isa.idl.idl.GeneralTerm#getNot()
   * @see #getGeneralTerm()
   * @generated
   */
  EAttribute getGeneralTerm_Not();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.GeneralTerm#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param</em>'.
   * @see es.us.isa.idl.idl.GeneralTerm#getParam()
   * @see #getGeneralTerm()
   * @generated
   */
  EReference getGeneralTerm_Param();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see es.us.isa.idl.idl.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.Param#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see es.us.isa.idl.idl.Param#getName()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Name();

  /**
   * Returns the meta object for the attribute list '{@link es.us.isa.idl.idl.Param#getStringValues <em>String Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>String Values</em>'.
   * @see es.us.isa.idl.idl.Param#getStringValues()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_StringValues();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.Param#getPatternString <em>Pattern String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pattern String</em>'.
   * @see es.us.isa.idl.idl.Param#getPatternString()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_PatternString();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.Param#getBooleanValue <em>Boolean Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Boolean Value</em>'.
   * @see es.us.isa.idl.idl.Param#getBooleanValue()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_BooleanValue();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.Param#getRelationalOp <em>Relational Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Relational Op</em>'.
   * @see es.us.isa.idl.idl.Param#getRelationalOp()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_RelationalOp();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.Param#getDoubleValue <em>Double Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Double Value</em>'.
   * @see es.us.isa.idl.idl.Param#getDoubleValue()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_DoubleValue();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.ParamValueRelation <em>Param Value Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param Value Relation</em>'.
   * @see es.us.isa.idl.idl.ParamValueRelation
   * @generated
   */
  EClass getParamValueRelation();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.GeneralClauseContinuation <em>General Clause Continuation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Clause Continuation</em>'.
   * @see es.us.isa.idl.idl.GeneralClauseContinuation
   * @generated
   */
  EClass getGeneralClauseContinuation();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.GeneralClauseContinuation#getLogicalOp <em>Logical Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Logical Op</em>'.
   * @see es.us.isa.idl.idl.GeneralClauseContinuation#getLogicalOp()
   * @see #getGeneralClauseContinuation()
   * @generated
   */
  EAttribute getGeneralClauseContinuation_LogicalOp();

  /**
   * Returns the meta object for the containment reference '{@link es.us.isa.idl.idl.GeneralClauseContinuation#getAdditionalElements <em>Additional Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Additional Elements</em>'.
   * @see es.us.isa.idl.idl.GeneralClauseContinuation#getAdditionalElements()
   * @see #getGeneralClauseContinuation()
   * @generated
   */
  EReference getGeneralClauseContinuation_AdditionalElements();

  /**
   * Returns the meta object for class '{@link es.us.isa.idl.idl.GeneralPredefinedDependency <em>General Predefined Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>General Predefined Dependency</em>'.
   * @see es.us.isa.idl.idl.GeneralPredefinedDependency
   * @generated
   */
  EClass getGeneralPredefinedDependency();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getNot <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Not</em>'.
   * @see es.us.isa.idl.idl.GeneralPredefinedDependency#getNot()
   * @see #getGeneralPredefinedDependency()
   * @generated
   */
  EAttribute getGeneralPredefinedDependency_Not();

  /**
   * Returns the meta object for the attribute '{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getPredefDepType <em>Predef Dep Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Predef Dep Type</em>'.
   * @see es.us.isa.idl.idl.GeneralPredefinedDependency#getPredefDepType()
   * @see #getGeneralPredefinedDependency()
   * @generated
   */
  EAttribute getGeneralPredefinedDependency_PredefDepType();

  /**
   * Returns the meta object for the containment reference list '{@link es.us.isa.idl.idl.GeneralPredefinedDependency#getPredefDepElements <em>Predef Dep Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predef Dep Elements</em>'.
   * @see es.us.isa.idl.idl.GeneralPredefinedDependency#getPredefDepElements()
   * @see #getGeneralPredefinedDependency()
   * @generated
   */
  EReference getGeneralPredefinedDependency_PredefDepElements();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IdlFactory getIdlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.ModelImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DEPENDENCIES = eINSTANCE.getModel_Dependencies();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.DependencyImpl <em>Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.DependencyImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getDependency()
     * @generated
     */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '<em><b>Dep</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY__DEP = eINSTANCE.getDependency_Dep();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.RelationalDependencyImpl <em>Relational Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.RelationalDependencyImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getRelationalDependency()
     * @generated
     */
    EClass RELATIONAL_DEPENDENCY = eINSTANCE.getRelationalDependency();

    /**
     * The meta object literal for the '<em><b>Param1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_DEPENDENCY__PARAM1 = eINSTANCE.getRelationalDependency_Param1();

    /**
     * The meta object literal for the '<em><b>Relational Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONAL_DEPENDENCY__RELATIONAL_OP = eINSTANCE.getRelationalDependency_RelationalOp();

    /**
     * The meta object literal for the '<em><b>Param2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_DEPENDENCY__PARAM2 = eINSTANCE.getRelationalDependency_Param2();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.ArithmeticDependencyImpl <em>Arithmetic Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.ArithmeticDependencyImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getArithmeticDependency()
     * @generated
     */
    EClass ARITHMETIC_DEPENDENCY = eINSTANCE.getArithmeticDependency();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITHMETIC_DEPENDENCY__OPERATION = eINSTANCE.getArithmeticDependency_Operation();

    /**
     * The meta object literal for the '<em><b>Relational Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARITHMETIC_DEPENDENCY__RELATIONAL_OP = eINSTANCE.getArithmeticDependency_RelationalOp();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARITHMETIC_DEPENDENCY__RESULT = eINSTANCE.getArithmeticDependency_Result();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.OperationImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>First Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__FIRST_PARAM = eINSTANCE.getOperation_FirstParam();

    /**
     * The meta object literal for the '<em><b>Operation Continuation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__OPERATION_CONTINUATION = eINSTANCE.getOperation_OperationContinuation();

    /**
     * The meta object literal for the '<em><b>Opening Parenthesis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OPENING_PARENTHESIS = eINSTANCE.getOperation_OpeningParenthesis();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION__OPERATION = eINSTANCE.getOperation_Operation();

    /**
     * The meta object literal for the '<em><b>Closing Parenthesis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__CLOSING_PARENTHESIS = eINSTANCE.getOperation_ClosingParenthesis();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.OperationContinuationImpl <em>Operation Continuation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.OperationContinuationImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getOperationContinuation()
     * @generated
     */
    EClass OPERATION_CONTINUATION = eINSTANCE.getOperationContinuation();

    /**
     * The meta object literal for the '<em><b>Arith Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION_CONTINUATION__ARITH_OP = eINSTANCE.getOperationContinuation_ArithOp();

    /**
     * The meta object literal for the '<em><b>Additional Params</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPERATION_CONTINUATION__ADDITIONAL_PARAMS = eINSTANCE.getOperationContinuation_AdditionalParams();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.ConditionalDependencyImpl <em>Conditional Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.ConditionalDependencyImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getConditionalDependency()
     * @generated
     */
    EClass CONDITIONAL_DEPENDENCY = eINSTANCE.getConditionalDependency();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL_DEPENDENCY__CONDITION = eINSTANCE.getConditionalDependency_Condition();

    /**
     * The meta object literal for the '<em><b>Consequence</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL_DEPENDENCY__CONSEQUENCE = eINSTANCE.getConditionalDependency_Consequence();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.GeneralPredicateImpl <em>General Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.GeneralPredicateImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralPredicate()
     * @generated
     */
    EClass GENERAL_PREDICATE = eINSTANCE.getGeneralPredicate();

    /**
     * The meta object literal for the '<em><b>First Clause</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_PREDICATE__FIRST_CLAUSE = eINSTANCE.getGeneralPredicate_FirstClause();

    /**
     * The meta object literal for the '<em><b>Clause Continuation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_PREDICATE__CLAUSE_CONTINUATION = eINSTANCE.getGeneralPredicate_ClauseContinuation();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.GeneralClauseImpl <em>General Clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.GeneralClauseImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralClause()
     * @generated
     */
    EClass GENERAL_CLAUSE = eINSTANCE.getGeneralClause();

    /**
     * The meta object literal for the '<em><b>First Element</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_CLAUSE__FIRST_ELEMENT = eINSTANCE.getGeneralClause_FirstElement();

    /**
     * The meta object literal for the '<em><b>Not</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CLAUSE__NOT = eINSTANCE.getGeneralClause_Not();

    /**
     * The meta object literal for the '<em><b>Opening Parenthesis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CLAUSE__OPENING_PARENTHESIS = eINSTANCE.getGeneralClause_OpeningParenthesis();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_CLAUSE__PREDICATE = eINSTANCE.getGeneralClause_Predicate();

    /**
     * The meta object literal for the '<em><b>Closing Parenthesis</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CLAUSE__CLOSING_PARENTHESIS = eINSTANCE.getGeneralClause_ClosingParenthesis();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.GeneralTermImpl <em>General Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.GeneralTermImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralTerm()
     * @generated
     */
    EClass GENERAL_TERM = eINSTANCE.getGeneralTerm();

    /**
     * The meta object literal for the '<em><b>Not</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_TERM__NOT = eINSTANCE.getGeneralTerm_Not();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_TERM__PARAM = eINSTANCE.getGeneralTerm_Param();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.ParamImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__NAME = eINSTANCE.getParam_Name();

    /**
     * The meta object literal for the '<em><b>String Values</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__STRING_VALUES = eINSTANCE.getParam_StringValues();

    /**
     * The meta object literal for the '<em><b>Pattern String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__PATTERN_STRING = eINSTANCE.getParam_PatternString();

    /**
     * The meta object literal for the '<em><b>Boolean Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__BOOLEAN_VALUE = eINSTANCE.getParam_BooleanValue();

    /**
     * The meta object literal for the '<em><b>Relational Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__RELATIONAL_OP = eINSTANCE.getParam_RelationalOp();

    /**
     * The meta object literal for the '<em><b>Double Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__DOUBLE_VALUE = eINSTANCE.getParam_DoubleValue();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.ParamValueRelationImpl <em>Param Value Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.ParamValueRelationImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getParamValueRelation()
     * @generated
     */
    EClass PARAM_VALUE_RELATION = eINSTANCE.getParamValueRelation();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.GeneralClauseContinuationImpl <em>General Clause Continuation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.GeneralClauseContinuationImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralClauseContinuation()
     * @generated
     */
    EClass GENERAL_CLAUSE_CONTINUATION = eINSTANCE.getGeneralClauseContinuation();

    /**
     * The meta object literal for the '<em><b>Logical Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_CLAUSE_CONTINUATION__LOGICAL_OP = eINSTANCE.getGeneralClauseContinuation_LogicalOp();

    /**
     * The meta object literal for the '<em><b>Additional Elements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_CLAUSE_CONTINUATION__ADDITIONAL_ELEMENTS = eINSTANCE.getGeneralClauseContinuation_AdditionalElements();

    /**
     * The meta object literal for the '{@link es.us.isa.idl.idl.impl.GeneralPredefinedDependencyImpl <em>General Predefined Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see es.us.isa.idl.idl.impl.GeneralPredefinedDependencyImpl
     * @see es.us.isa.idl.idl.impl.IdlPackageImpl#getGeneralPredefinedDependency()
     * @generated
     */
    EClass GENERAL_PREDEFINED_DEPENDENCY = eINSTANCE.getGeneralPredefinedDependency();

    /**
     * The meta object literal for the '<em><b>Not</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_PREDEFINED_DEPENDENCY__NOT = eINSTANCE.getGeneralPredefinedDependency_Not();

    /**
     * The meta object literal for the '<em><b>Predef Dep Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERAL_PREDEFINED_DEPENDENCY__PREDEF_DEP_TYPE = eINSTANCE.getGeneralPredefinedDependency_PredefDepType();

    /**
     * The meta object literal for the '<em><b>Predef Dep Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERAL_PREDEFINED_DEPENDENCY__PREDEF_DEP_ELEMENTS = eINSTANCE.getGeneralPredefinedDependency_PredefDepElements();

  }

} //IdlPackage
