/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation Continuation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.OperationContinuation#getArithOp <em>Arith Op</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.OperationContinuation#getAdditionalParams <em>Additional Params</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getOperationContinuation()
 * @model
 * @generated
 */
public interface OperationContinuation extends EObject
{
  /**
   * Returns the value of the '<em><b>Arith Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arith Op</em>' attribute.
   * @see #setArithOp(String)
   * @see es.us.isa.idl.idl.IdlPackage#getOperationContinuation_ArithOp()
   * @model
   * @generated
   */
  String getArithOp();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.OperationContinuation#getArithOp <em>Arith Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arith Op</em>' attribute.
   * @see #getArithOp()
   * @generated
   */
  void setArithOp(String value);

  /**
   * Returns the value of the '<em><b>Additional Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additional Params</em>' containment reference.
   * @see #setAdditionalParams(EObject)
   * @see es.us.isa.idl.idl.IdlPackage#getOperationContinuation_AdditionalParams()
   * @model containment="true"
   * @generated
   */
  EObject getAdditionalParams();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.OperationContinuation#getAdditionalParams <em>Additional Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additional Params</em>' containment reference.
   * @see #getAdditionalParams()
   * @generated
   */
  void setAdditionalParams(EObject value);

} // OperationContinuation
