/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.Operation#getFirstParam <em>First Param</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.Operation#getOperationContinuation <em>Operation Continuation</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.Operation#getOpeningParenthesis <em>Opening Parenthesis</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.Operation#getOperation <em>Operation</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.Operation#getClosingParenthesis <em>Closing Parenthesis</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends EObject
{
  /**
   * Returns the value of the '<em><b>First Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Param</em>' containment reference.
   * @see #setFirstParam(Param)
   * @see es.us.isa.idl.idl.IdlPackage#getOperation_FirstParam()
   * @model containment="true"
   * @generated
   */
  Param getFirstParam();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.Operation#getFirstParam <em>First Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Param</em>' containment reference.
   * @see #getFirstParam()
   * @generated
   */
  void setFirstParam(Param value);

  /**
   * Returns the value of the '<em><b>Operation Continuation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation Continuation</em>' containment reference.
   * @see #setOperationContinuation(OperationContinuation)
   * @see es.us.isa.idl.idl.IdlPackage#getOperation_OperationContinuation()
   * @model containment="true"
   * @generated
   */
  OperationContinuation getOperationContinuation();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.Operation#getOperationContinuation <em>Operation Continuation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation Continuation</em>' containment reference.
   * @see #getOperationContinuation()
   * @generated
   */
  void setOperationContinuation(OperationContinuation value);

  /**
   * Returns the value of the '<em><b>Opening Parenthesis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opening Parenthesis</em>' attribute.
   * @see #setOpeningParenthesis(String)
   * @see es.us.isa.idl.idl.IdlPackage#getOperation_OpeningParenthesis()
   * @model
   * @generated
   */
  String getOpeningParenthesis();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.Operation#getOpeningParenthesis <em>Opening Parenthesis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Opening Parenthesis</em>' attribute.
   * @see #getOpeningParenthesis()
   * @generated
   */
  void setOpeningParenthesis(String value);

  /**
   * Returns the value of the '<em><b>Operation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' containment reference.
   * @see #setOperation(Operation)
   * @see es.us.isa.idl.idl.IdlPackage#getOperation_Operation()
   * @model containment="true"
   * @generated
   */
  Operation getOperation();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.Operation#getOperation <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' containment reference.
   * @see #getOperation()
   * @generated
   */
  void setOperation(Operation value);

  /**
   * Returns the value of the '<em><b>Closing Parenthesis</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Closing Parenthesis</em>' attribute.
   * @see #setClosingParenthesis(String)
   * @see es.us.isa.idl.idl.IdlPackage#getOperation_ClosingParenthesis()
   * @model
   * @generated
   */
  String getClosingParenthesis();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.Operation#getClosingParenthesis <em>Closing Parenthesis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Closing Parenthesis</em>' attribute.
   * @see #getClosingParenthesis()
   * @generated
   */
  void setClosingParenthesis(String value);

} // Operation
