/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Param Value Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see es.us.isa.idl.idl.IdlPackage#getParamValueRelation()
 * @model
 * @generated
 */
public interface ParamValueRelation extends EObject
{
} // ParamValueRelation
