/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relational Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.RelationalDependency#getParam1 <em>Param1</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.RelationalDependency#getRelationalOp <em>Relational Op</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.RelationalDependency#getParam2 <em>Param2</em>}</li>
 * </ul>
 *
 * @see es.us.isa.idl.idl.IdlPackage#getRelationalDependency()
 * @model
 * @generated
 */
public interface RelationalDependency extends GeneralTerm
{
  /**
   * Returns the value of the '<em><b>Param1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param1</em>' containment reference.
   * @see #setParam1(Param)
   * @see es.us.isa.idl.idl.IdlPackage#getRelationalDependency_Param1()
   * @model containment="true"
   * @generated
   */
  Param getParam1();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.RelationalDependency#getParam1 <em>Param1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param1</em>' containment reference.
   * @see #getParam1()
   * @generated
   */
  void setParam1(Param value);

  /**
   * Returns the value of the '<em><b>Relational Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational Op</em>' attribute.
   * @see #setRelationalOp(String)
   * @see es.us.isa.idl.idl.IdlPackage#getRelationalDependency_RelationalOp()
   * @model
   * @generated
   */
  String getRelationalOp();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.RelationalDependency#getRelationalOp <em>Relational Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational Op</em>' attribute.
   * @see #getRelationalOp()
   * @generated
   */
  void setRelationalOp(String value);

  /**
   * Returns the value of the '<em><b>Param2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param2</em>' containment reference.
   * @see #setParam2(Param)
   * @see es.us.isa.idl.idl.IdlPackage#getRelationalDependency_Param2()
   * @model containment="true"
   * @generated
   */
  Param getParam2();

  /**
   * Sets the value of the '{@link es.us.isa.idl.idl.RelationalDependency#getParam2 <em>Param2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param2</em>' containment reference.
   * @see #getParam2()
   * @generated
   */
  void setParam2(Param value);

} // RelationalDependency
