/*
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link IDLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractIDLWebModule extends DefaultWebModule {

}
