/**
 * generated by Xtext 2.30.0
 */
package es.us.isa.idl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IDLIdeModule extends AbstractIDLIdeModule {
}
