/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import es.us.isa.idl.IDLRuntimeModule;
import es.us.isa.idl.IDLStandaloneSetup;
import es.us.isa.idl.ide.IDLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class IDLWebSetup extends IDLStandaloneSetup {
  @Override
  public Injector createInjector() {
    IDLRuntimeModule _iDLRuntimeModule = new IDLRuntimeModule();
    IDLIdeModule _iDLIdeModule = new IDLIdeModule();
    IDLWebModule _iDLWebModule = new IDLWebModule();
    return Guice.createInjector(Modules2.mixin(_iDLRuntimeModule, _iDLIdeModule, _iDLWebModule));
  }
}
