/**
 * generated by Xtext 2.30.0
 */
package es.us.isa.idl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IDLRuntimeModule extends AbstractIDLRuntimeModule {
}
