/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl.impl;

import es.us.isa.idl.idl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class IdlFactoryImpl extends EFactoryImpl implements IdlFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static IdlFactory init()
  {
    try
    {
      IdlFactory theIdlFactory = (IdlFactory)EPackage.Registry.INSTANCE.getEFactory(IdlPackage.eNS_URI);
      if (theIdlFactory != null)
      {
        return theIdlFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new IdlFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IdlFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case IdlPackage.MODEL: return createModel();
      case IdlPackage.DEPENDENCY: return createDependency();
      case IdlPackage.RELATIONAL_DEPENDENCY: return createRelationalDependency();
      case IdlPackage.ARITHMETIC_DEPENDENCY: return createArithmeticDependency();
      case IdlPackage.OPERATION: return createOperation();
      case IdlPackage.OPERATION_CONTINUATION: return createOperationContinuation();
      case IdlPackage.CONDITIONAL_DEPENDENCY: return createConditionalDependency();
      case IdlPackage.GENERAL_PREDICATE: return createGeneralPredicate();
      case IdlPackage.GENERAL_CLAUSE: return createGeneralClause();
      case IdlPackage.GENERAL_TERM: return createGeneralTerm();
      case IdlPackage.PARAM: return createParam();
      case IdlPackage.PARAM_VALUE_RELATION: return createParamValueRelation();
      case IdlPackage.GENERAL_CLAUSE_CONTINUATION: return createGeneralClauseContinuation();
      case IdlPackage.GENERAL_PREDEFINED_DEPENDENCY: return createGeneralPredefinedDependency();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Dependency createDependency()
  {
    DependencyImpl dependency = new DependencyImpl();
    return dependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RelationalDependency createRelationalDependency()
  {
    RelationalDependencyImpl relationalDependency = new RelationalDependencyImpl();
    return relationalDependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ArithmeticDependency createArithmeticDependency()
  {
    ArithmeticDependencyImpl arithmeticDependency = new ArithmeticDependencyImpl();
    return arithmeticDependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation createOperation()
  {
    OperationImpl operation = new OperationImpl();
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationContinuation createOperationContinuation()
  {
    OperationContinuationImpl operationContinuation = new OperationContinuationImpl();
    return operationContinuation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConditionalDependency createConditionalDependency()
  {
    ConditionalDependencyImpl conditionalDependency = new ConditionalDependencyImpl();
    return conditionalDependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralPredicate createGeneralPredicate()
  {
    GeneralPredicateImpl generalPredicate = new GeneralPredicateImpl();
    return generalPredicate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralClause createGeneralClause()
  {
    GeneralClauseImpl generalClause = new GeneralClauseImpl();
    return generalClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralTerm createGeneralTerm()
  {
    GeneralTermImpl generalTerm = new GeneralTermImpl();
    return generalTerm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Param createParam()
  {
    ParamImpl param = new ParamImpl();
    return param;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ParamValueRelation createParamValueRelation()
  {
    ParamValueRelationImpl paramValueRelation = new ParamValueRelationImpl();
    return paramValueRelation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralClauseContinuation createGeneralClauseContinuation()
  {
    GeneralClauseContinuationImpl generalClauseContinuation = new GeneralClauseContinuationImpl();
    return generalClauseContinuation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneralPredefinedDependency createGeneralPredefinedDependency()
  {
    GeneralPredefinedDependencyImpl generalPredefinedDependency = new GeneralPredefinedDependencyImpl();
    return generalPredefinedDependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IdlPackage getIdlPackage()
  {
    return (IdlPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static IdlPackage getPackage()
  {
    return IdlPackage.eINSTANCE;
  }

} //IdlFactoryImpl
