/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl.impl;

import es.us.isa.idl.idl.IdlPackage;
import es.us.isa.idl.idl.OperationContinuation;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation Continuation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.impl.OperationContinuationImpl#getArithOp <em>Arith Op</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.impl.OperationContinuationImpl#getAdditionalParams <em>Additional Params</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperationContinuationImpl extends MinimalEObjectImpl.Container implements OperationContinuation
{
  /**
   * The default value of the '{@link #getArithOp() <em>Arith Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArithOp()
   * @generated
   * @ordered
   */
  protected static final String ARITH_OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArithOp() <em>Arith Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArithOp()
   * @generated
   * @ordered
   */
  protected String arithOp = ARITH_OP_EDEFAULT;

  /**
   * The cached value of the '{@link #getAdditionalParams() <em>Additional Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdditionalParams()
   * @generated
   * @ordered
   */
  protected EObject additionalParams;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationContinuationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdlPackage.Literals.OPERATION_CONTINUATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getArithOp()
  {
    return arithOp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArithOp(String newArithOp)
  {
    String oldArithOp = arithOp;
    arithOp = newArithOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION_CONTINUATION__ARITH_OP, oldArithOp, arithOp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject getAdditionalParams()
  {
    return additionalParams;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAdditionalParams(EObject newAdditionalParams, NotificationChain msgs)
  {
    EObject oldAdditionalParams = additionalParams;
    additionalParams = newAdditionalParams;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS, oldAdditionalParams, newAdditionalParams);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAdditionalParams(EObject newAdditionalParams)
  {
    if (newAdditionalParams != additionalParams)
    {
      NotificationChain msgs = null;
      if (additionalParams != null)
        msgs = ((InternalEObject)additionalParams).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS, null, msgs);
      if (newAdditionalParams != null)
        msgs = ((InternalEObject)newAdditionalParams).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS, null, msgs);
      msgs = basicSetAdditionalParams(newAdditionalParams, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS, newAdditionalParams, newAdditionalParams));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS:
        return basicSetAdditionalParams(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION_CONTINUATION__ARITH_OP:
        return getArithOp();
      case IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS:
        return getAdditionalParams();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION_CONTINUATION__ARITH_OP:
        setArithOp((String)newValue);
        return;
      case IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS:
        setAdditionalParams((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION_CONTINUATION__ARITH_OP:
        setArithOp(ARITH_OP_EDEFAULT);
        return;
      case IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS:
        setAdditionalParams((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION_CONTINUATION__ARITH_OP:
        return ARITH_OP_EDEFAULT == null ? arithOp != null : !ARITH_OP_EDEFAULT.equals(arithOp);
      case IdlPackage.OPERATION_CONTINUATION__ADDITIONAL_PARAMS:
        return additionalParams != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (arithOp: ");
    result.append(arithOp);
    result.append(')');
    return result.toString();
  }

} //OperationContinuationImpl
