/**
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.idl.impl;

import es.us.isa.idl.idl.IdlPackage;
import es.us.isa.idl.idl.Operation;
import es.us.isa.idl.idl.OperationContinuation;
import es.us.isa.idl.idl.Param;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.idl.idl.impl.OperationImpl#getFirstParam <em>First Param</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.impl.OperationImpl#getOperationContinuation <em>Operation Continuation</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.impl.OperationImpl#getOpeningParenthesis <em>Opening Parenthesis</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.impl.OperationImpl#getOperation <em>Operation</em>}</li>
 *   <li>{@link es.us.isa.idl.idl.impl.OperationImpl#getClosingParenthesis <em>Closing Parenthesis</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OperationImpl extends MinimalEObjectImpl.Container implements Operation
{
  /**
   * The cached value of the '{@link #getFirstParam() <em>First Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFirstParam()
   * @generated
   * @ordered
   */
  protected Param firstParam;

  /**
   * The cached value of the '{@link #getOperationContinuation() <em>Operation Continuation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperationContinuation()
   * @generated
   * @ordered
   */
  protected OperationContinuation operationContinuation;

  /**
   * The default value of the '{@link #getOpeningParenthesis() <em>Opening Parenthesis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpeningParenthesis()
   * @generated
   * @ordered
   */
  protected static final String OPENING_PARENTHESIS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOpeningParenthesis() <em>Opening Parenthesis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpeningParenthesis()
   * @generated
   * @ordered
   */
  protected String openingParenthesis = OPENING_PARENTHESIS_EDEFAULT;

  /**
   * The cached value of the '{@link #getOperation() <em>Operation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperation()
   * @generated
   * @ordered
   */
  protected Operation operation;

  /**
   * The default value of the '{@link #getClosingParenthesis() <em>Closing Parenthesis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClosingParenthesis()
   * @generated
   * @ordered
   */
  protected static final String CLOSING_PARENTHESIS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getClosingParenthesis() <em>Closing Parenthesis</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClosingParenthesis()
   * @generated
   * @ordered
   */
  protected String closingParenthesis = CLOSING_PARENTHESIS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdlPackage.Literals.OPERATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Param getFirstParam()
  {
    return firstParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFirstParam(Param newFirstParam, NotificationChain msgs)
  {
    Param oldFirstParam = firstParam;
    firstParam = newFirstParam;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__FIRST_PARAM, oldFirstParam, newFirstParam);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFirstParam(Param newFirstParam)
  {
    if (newFirstParam != firstParam)
    {
      NotificationChain msgs = null;
      if (firstParam != null)
        msgs = ((InternalEObject)firstParam).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION__FIRST_PARAM, null, msgs);
      if (newFirstParam != null)
        msgs = ((InternalEObject)newFirstParam).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION__FIRST_PARAM, null, msgs);
      msgs = basicSetFirstParam(newFirstParam, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__FIRST_PARAM, newFirstParam, newFirstParam));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OperationContinuation getOperationContinuation()
  {
    return operationContinuation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperationContinuation(OperationContinuation newOperationContinuation, NotificationChain msgs)
  {
    OperationContinuation oldOperationContinuation = operationContinuation;
    operationContinuation = newOperationContinuation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__OPERATION_CONTINUATION, oldOperationContinuation, newOperationContinuation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperationContinuation(OperationContinuation newOperationContinuation)
  {
    if (newOperationContinuation != operationContinuation)
    {
      NotificationChain msgs = null;
      if (operationContinuation != null)
        msgs = ((InternalEObject)operationContinuation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION__OPERATION_CONTINUATION, null, msgs);
      if (newOperationContinuation != null)
        msgs = ((InternalEObject)newOperationContinuation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION__OPERATION_CONTINUATION, null, msgs);
      msgs = basicSetOperationContinuation(newOperationContinuation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__OPERATION_CONTINUATION, newOperationContinuation, newOperationContinuation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOpeningParenthesis()
  {
    return openingParenthesis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOpeningParenthesis(String newOpeningParenthesis)
  {
    String oldOpeningParenthesis = openingParenthesis;
    openingParenthesis = newOpeningParenthesis;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__OPENING_PARENTHESIS, oldOpeningParenthesis, openingParenthesis));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation getOperation()
  {
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOperation(Operation newOperation, NotificationChain msgs)
  {
    Operation oldOperation = operation;
    operation = newOperation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__OPERATION, oldOperation, newOperation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperation(Operation newOperation)
  {
    if (newOperation != operation)
    {
      NotificationChain msgs = null;
      if (operation != null)
        msgs = ((InternalEObject)operation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION__OPERATION, null, msgs);
      if (newOperation != null)
        msgs = ((InternalEObject)newOperation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IdlPackage.OPERATION__OPERATION, null, msgs);
      msgs = basicSetOperation(newOperation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__OPERATION, newOperation, newOperation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getClosingParenthesis()
  {
    return closingParenthesis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClosingParenthesis(String newClosingParenthesis)
  {
    String oldClosingParenthesis = closingParenthesis;
    closingParenthesis = newClosingParenthesis;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.OPERATION__CLOSING_PARENTHESIS, oldClosingParenthesis, closingParenthesis));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION__FIRST_PARAM:
        return basicSetFirstParam(null, msgs);
      case IdlPackage.OPERATION__OPERATION_CONTINUATION:
        return basicSetOperationContinuation(null, msgs);
      case IdlPackage.OPERATION__OPERATION:
        return basicSetOperation(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION__FIRST_PARAM:
        return getFirstParam();
      case IdlPackage.OPERATION__OPERATION_CONTINUATION:
        return getOperationContinuation();
      case IdlPackage.OPERATION__OPENING_PARENTHESIS:
        return getOpeningParenthesis();
      case IdlPackage.OPERATION__OPERATION:
        return getOperation();
      case IdlPackage.OPERATION__CLOSING_PARENTHESIS:
        return getClosingParenthesis();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION__FIRST_PARAM:
        setFirstParam((Param)newValue);
        return;
      case IdlPackage.OPERATION__OPERATION_CONTINUATION:
        setOperationContinuation((OperationContinuation)newValue);
        return;
      case IdlPackage.OPERATION__OPENING_PARENTHESIS:
        setOpeningParenthesis((String)newValue);
        return;
      case IdlPackage.OPERATION__OPERATION:
        setOperation((Operation)newValue);
        return;
      case IdlPackage.OPERATION__CLOSING_PARENTHESIS:
        setClosingParenthesis((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION__FIRST_PARAM:
        setFirstParam((Param)null);
        return;
      case IdlPackage.OPERATION__OPERATION_CONTINUATION:
        setOperationContinuation((OperationContinuation)null);
        return;
      case IdlPackage.OPERATION__OPENING_PARENTHESIS:
        setOpeningParenthesis(OPENING_PARENTHESIS_EDEFAULT);
        return;
      case IdlPackage.OPERATION__OPERATION:
        setOperation((Operation)null);
        return;
      case IdlPackage.OPERATION__CLOSING_PARENTHESIS:
        setClosingParenthesis(CLOSING_PARENTHESIS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.OPERATION__FIRST_PARAM:
        return firstParam != null;
      case IdlPackage.OPERATION__OPERATION_CONTINUATION:
        return operationContinuation != null;
      case IdlPackage.OPERATION__OPENING_PARENTHESIS:
        return OPENING_PARENTHESIS_EDEFAULT == null ? openingParenthesis != null : !OPENING_PARENTHESIS_EDEFAULT.equals(openingParenthesis);
      case IdlPackage.OPERATION__OPERATION:
        return operation != null;
      case IdlPackage.OPERATION__CLOSING_PARENTHESIS:
        return CLOSING_PARENTHESIS_EDEFAULT == null ? closingParenthesis != null : !CLOSING_PARENTHESIS_EDEFAULT.equals(closingParenthesis);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (openingParenthesis: ");
    result.append(openingParenthesis);
    result.append(", closingParenthesis: ");
    result.append(closingParenthesis);
    result.append(')');
    return result.toString();
  }

} //OperationImpl
