/**
 * generated by Xtext 2.30.0
 */
package es.us.isa.idl.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class IDLScopeProvider extends AbstractIDLScopeProvider {
}
