/**
 * generated by Xtext 2.30.0
 */
package es.us.isa.idl.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IDLValidator extends AbstractIDLValidator {
}
