/*
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.ide

import com.google.inject.Guice
import es.us.isa.idl.IDLRuntimeModule
import es.us.isa.idl.IDLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class IDLIdeSetup extends IDLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new IDLRuntimeModule, new IDLIdeModule))
	}
	
}
