/*
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class IDLRuntimeModule extends AbstractIDLRuntimeModule {
}
