/*
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class IDLStandaloneSetup extends IDLStandaloneSetupGenerated {

	def static void doSetup() {
		new IDLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
