/*
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("es/us/isa/idl/parser/antlr/internal/InternalIDL.tokens");
	}
}
