/*
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.parser.antlr;

import com.google.inject.Inject;
import es.us.isa.idl.parser.antlr.internal.InternalIDLParser;
import es.us.isa.idl.services.IDLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IDLParser extends AbstractAntlrParser {

	@Inject
	private IDLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIDLParser createParser(XtextTokenStream stream) {
		return new InternalIDLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public IDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
