/*
 * generated by Xtext 2.25.0
 */
package es.us.isa.idl.ui.tests;

import com.google.inject.Injector;
import es.us.isa.idl.ui.internal.IdlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IdlActivator.getInstance().getInjector("es.us.isa.idl.IDL");
	}

}
